// Familles de mots proches. À chaque partie, deux mots sont tirés dans une même
// famille : l'un pour les Civils, l'autre pour les Undercover. Chercher son mot
// ici ne dit donc pas lequel des autres est en jeu.
export const GROUPS = [
  ["Chat", "Chien", "Lapin", "Hamster", "Furet"],
  ["Café", "Thé", "Chocolat chaud", "Tisane", "Cappuccino"],
  ["Plage", "Piscine", "Lac", "Rivière", "Port"],
  ["Guitare", "Violon", "Harpe", "Banjo", "Contrebasse"],
  ["Pizza", "Burger", "Kebab", "Tacos", "Sandwich"],
  ["Train", "Métro", "Tramway", "Bus", "Funiculaire"],
  ["Lune", "Soleil", "Étoile", "Comète", "Planète"],
  ["Pomme", "Poire", "Pêche", "Abricot", "Prune"],
  ["Football", "Rugby", "Handball", "Basket", "Volley"],
  ["Cinéma", "Théâtre", "Opéra", "Cirque", "Concert"],
  ["Médecin", "Infirmier", "Dentiste", "Pharmacien", "Vétérinaire"],
  ["Pirate", "Corsaire", "Viking", "Chevalier", "Mousquetaire"],
  ["Vampire", "Zombie", "Fantôme", "Momie", "Loup-garou"],
  ["Château", "Palais", "Manoir", "Forteresse", "Cathédrale"],
  ["Montagne", "Colline", "Volcan", "Falaise", "Dune"],
  ["Avion", "Hélicoptère", "Montgolfière", "Planeur", "Fusée"],
  ["Vélo", "Trottinette", "Skateboard", "Rollers", "Moto"],
  ["Croissant", "Pain au chocolat", "Brioche", "Chausson aux pommes", "Baguette"],
  ["Vin", "Bière", "Cidre", "Champagne", "Limonade"],
  ["Neige", "Glace", "Grêle", "Givre", "Brouillard"],
  ["Roi", "Empereur", "Prince", "Président", "Pharaon"],
  ["Sorcière", "Fée", "Magicien", "Lutin", "Sirène"],
  ["Lion", "Tigre", "Panthère", "Guépard", "Lynx"],
  ["Requin", "Dauphin", "Baleine", "Orque", "Phoque"],
  ["Abeille", "Guêpe", "Bourdon", "Mouche", "Moustique"],
  ["Bibliothèque", "Librairie", "Musée", "Kiosque", "École"],
  ["Stylo", "Crayon", "Feutre", "Pinceau", "Craie"],
  ["Téléphone", "Tablette", "Ordinateur", "Télévision", "Radio"],
  ["Camping", "Hôtel", "Auberge", "Gîte", "Cabane"],
  ["Mariage", "Anniversaire", "Baptême", "Noël", "Nouvel An"],
  ["Chocolat", "Caramel", "Nougat", "Réglisse", "Guimauve"],
  ["Crêpe", "Gaufre", "Beignet", "Churros", "Pancake"],
  ["Frites", "Chips", "Purée", "Gratin", "Raclette"],
  ["Fourchette", "Cuillère", "Couteau", "Baguettes", "Louche"],
  ["Canapé", "Fauteuil", "Tabouret", "Hamac", "Banc"],
  ["Parapluie", "Imperméable", "Écharpe", "Bonnet", "Gants"],
  ["Baskets", "Chaussons", "Bottes", "Sandales", "Tongs"],
  ["Montre", "Horloge", "Réveil", "Sablier", "Chronomètre"],
  ["Bougie", "Lampe", "Lanterne", "Torche", "Phare"],
  ["Policier", "Détective", "Gendarme", "Espion", "Juge"],
  ["Tennis", "Ping-pong", "Badminton", "Squash", "Pétanque"],
  ["Ski", "Snowboard", "Luge", "Patinage", "Surf"],
  ["Échecs", "Dames", "Dominos", "Petits chevaux", "Belote"],
  ["Désert", "Savane", "Jungle", "Banquise", "Steppe"],

  // Jeux vidéo
  ["Mario", "Sonic", "Kirby", "Donkey Kong", "Crash Bandicoot"],
  ["Minecraft", "Fortnite", "Roblox", "Among Us", "Fall Guys"],
  ["Zelda", "Final Fantasy", "Skyrim", "Elden Ring", "The Witcher"],
  ["PlayStation", "Xbox", "Switch", "Game Boy", "Steam Deck"],
  ["FIFA", "Rocket League", "NBA 2K", "Mario Kart", "Gran Turismo"],
  ["Call of Duty", "Valorant", "Overwatch", "Counter-Strike", "Apex Legends"],
  ["League of Legends", "Dota", "Clash Royale", "Brawl Stars", "Clash of Clans"],
  ["Pikachu", "Dracaufeu", "Évoli", "Mewtwo", "Ronflex"],
  ["Tetris", "Pac-Man", "Candy Crush", "Snake", "Space Invaders"],
  ["GTA", "Red Dead Redemption", "Cyberpunk", "Assassin's Creed", "Watch Dogs"],

  // Manga et animé
  ["Naruto", "One Piece", "Dragon Ball", "Bleach", "Hunter x Hunter"],
  ["Luffy", "Goku", "Ichigo", "Gon", "Deku"],
  ["Sasuke", "Vegeta", "Zoro", "Kirua", "Bakugo"],
  ["L'Attaque des Titans", "Demon Slayer", "Jujutsu Kaisen", "Chainsaw Man", "Tokyo Ghoul"],
  ["Death Note", "Code Geass", "Fullmetal Alchemist", "Steins;Gate", "Monster"],
  ["Totoro", "Chihiro", "Mononoké", "Ponyo", "Kiki"],
  ["Sharingan", "Kamehameha", "Bankai", "Haki", "Nen"],
  ["Hokage", "Pirate", "Shinigami", "Super Saiyan", "Alchimiste"],
  ["Pokémon", "Digimon", "Yu-Gi-Oh!", "Beyblade", "Inazuma Eleven"],
  ["Haikyu", "Captain Tsubasa", "Slam Dunk", "Blue Lock", "Kuroko's Basket"]
];
